/*eslint-disable @nx/enforce-module-boundaries */
import 'homepage/styles.css';
import styles from 'homepage/app/app.module.css';
import { Footer } from 'homepage/app/components/Footer';

export const metadata = {
  title: 'React Dialog server-rendered example',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <header>
            <h1>HTML native dialogs in React</h1>
          </header>
          <main className={styles.content}>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
