name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or the branch you want to deploy from

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # specify the version of Node.js you need

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn

      - name: Build the library
        run: yarn nx build react-dialog

      - name: Build homepage
        run: yarn nx build homepage

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          # Upload content of ./src directory from the repository
          path: './dist/packages/homepage'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
