name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # specify the version of Node.js you need

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn

      - name: Build the library
        run: yarn nx build react-dialog

      - name: Build homepage
        run: yarn nx build homepage

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/packages/homepage # the directory to publish to GitHub Pages
